image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GITLAB_CI: 1

services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add --no-cache make bash && rm -rf /var/cache/apk/*

stages:
  - build
  - deploy

.general_scripts: &general_scripts
  - make info

build:
  stage: build
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  script:
    - make build-test
    - make start-test
    - docker ps -a
    - make wait-for-db
    - make drop-migrate
    - make seed
    - *general_scripts
    - make phpunit
    - make composer-audit
    - make ecs
    - make phpcs
    - make phpstan
    - make phpinsights
    - make phpmd
    - make phpcpd
    - make down-test
  artifacts:
    paths:
      - reports/
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

push_staging_images:
  stage: deploy
  script:
    - make build-staging
    # TODO: set necessary image name in compose-staging.yaml according to your registry and edit lines bellow
    #- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    #- docker compose -f compose-staging.yaml push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^release.*$/'

push_prod_images:
  stage: deploy
  script:
    - make build-prod
    # TODO: set necessary image name in compose-prod.yaml according to your registry and edit lines bellow
    #- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    #- docker compose -f compose-prod.yaml push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH =~ /^release.*$/'
