; ==============================================================================
; PHP-FPM 'www' pool configuration
;
; Full documentation, default values, and all available directives:
; https://github.com/php/php-src/blob/master/sapi/fpm/www.conf.in
; ==============================================================================

[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000

clear_env = no
catch_workers_output = yes
decorate_workers_output = no

pm = dynamic
pm.max_children = 150
pm.start_servers = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 50

pm.max_requests = 500

request_terminate_timeout = 60s
request_slowlog_timeout = 30s
slowlog = /proc/self/fd/2

ping.path = /ping
pm.status_path = /status
